spring:
  web:
    #静态资源处理
    resources:
      #启动默认静态资源处理，默认启用
      cache:
        cachecontrol:
          #缓存相应时间，单位秒
          max-age: 3600
      chain:
        #资源链启动缓存，默认启动
        cache: true
        #启用资源链，默认禁用
        enabled: true
        #启用压缩资源(gzip,brotli)解析，默认禁用
        compressed: true
        #启用h5应用缓存，默认禁用
        html-application-cache: true
      static-locations: classpath:/static/

  #RabbitMQ
  rabbitmq:
    #服务器
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #自启动
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试
        enabled: true
        #重试时间
        initial-interval: 1000ms
        #重试最大次数
        max-attempts: 3
        #重试最大时间间隔
        max-interval: 10000ms
        #重试的间隔乘数
        multiplier: 1

  # thymeleaf配置
  thymeleaf:
    #关闭缓存
    cache: false
    #mysql5.7,数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认（10min)
      idle-timeout: 1800000
      #最大连接数，默认10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commid: true
      #连接最大存活时间，0表示永久存活，默认1800000（30分钟)
      max-lifetime: 1800000
      #连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

#redis配置
  redis:
    #服务器地址
    host: localhost
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #超时时间
    timeout: 10000ms
    #redis2.x版本默认使用lettuce实现，与1.x版本使用jedis实现，最大区别是：lettuce线程安全！
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接阻塞等待时间
        max-wait: 10000ms
        #最大空闲连接数
        max-idle: 200
        #最小空闲连接数
        min-idle: 5

#mybatis_plus配置
mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.wang.seckill.pojo

#MyBatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.wang.seckill.mapper: debug